# Generated by Django 5.1.15 on 2026-09-15 02:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número de Periodo (1-4)')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre del Periodo')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Finalización')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Ponderación Anual (%)')),
                ('status', models.CharField(choices=[('ACTIVE', '🟢 Abierto / Activo'), ('CLOSED', '🟡 Cerrado'), ('LOCKED', '🔴 Bloqueado')], db_index=True, default='ACTIVE', max_length=15, verbose_name='Estado del Periodo')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='courses.academicyear', verbose_name='Año Lectivo')),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'ordering': ['academic_year', 'number'],
                'unique_together': {('academic_year', 'number')},
            },
        ),
    ]
