# Generated by Django 5.1.15 on 2026-09-15 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje descriptivo')),
                ('level', models.CharField(choices=[('BLOCK', '🔴 Bloqueo Crítico'), ('WARNING', '🟡 Advertencia'), ('INFO', '🔵 Información')], db_index=True, default='INFO', max_length=15, verbose_name='Nivel de Alerta')),
                ('target_role', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rol Destinatario (Opcional)')),
                ('is_dismissible', models.BooleanField(default=True, verbose_name='¿Es Descartable?')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='¿Está Activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Destinatario')),
            ],
            options={
                'verbose_name': 'Alerta del Sistema',
                'verbose_name_plural': 'Alertas del Sistema',
                'ordering': ['-created_at'],
            },
        ),
    ]
