# Generated by Django 5.2.8 on 2026-09-16 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Título de la Actividad')),
                ('description', models.TextField(verbose_name='Descripción de la Actividad')),
                ('event_date', models.DateField(verbose_name='Fecha de la Actividad')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Hora de la Actividad')),
                ('location', models.CharField(default='Instalaciones del Colegio', max_length=120, verbose_name='Lugar / Espacio')),
                ('target_audience', models.CharField(choices=[('ALL', 'Toda la Comunidad'), ('STUDENTS', 'Solo Estudiantes'), ('TEACHERS', 'Solo Docentes'), ('PARENTS', 'Solo Padres y Acudientes')], default='ALL', max_length=20, verbose_name='Dirigido a')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Actividad Vigente?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='Programado por')),
            ],
            options={
                'verbose_name': 'Actividad Institucional',
                'verbose_name_plural': 'Actividades Institucionales',
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
