# Generated by Django 5.1.15 on 2026-09-15 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Código Estudiantil / Folio')),
                ('blood_type', models.CharField(default='O+', max_length=5, verbose_name='Grupo y Factor RH')),
                ('eps', models.CharField(blank=True, max_length=80, null=True, verbose_name='Entidad Promotora de Salud (EPS)')),
                ('medical_notes', models.TextField(blank=True, null=True, verbose_name='Observaciones Médicas / Alergias')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_students', to=settings.AUTH_USER_MODEL, verbose_name='Padre de Familia / Acudiente')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Institucional')),
            ],
            options={
                'verbose_name': 'Expediente Estudiantil',
                'verbose_name_plural': 'Expedientes Estudiantiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Matrícula')),
                ('status', models.CharField(choices=[('ACTIVE', '🟢 Matriculado / Activo'), ('TRANSFERRED', '🔵 Trasladado de Grupo'), ('WITHDRAWN', '🔴 Retirado / Desertor'), ('PROMOTED', '🎓 Promovido de Grado'), ('FAILED', '❌ No Promovido')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Estado de Matrícula')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.academicyear', verbose_name='Año Lectivo')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.coursesection', verbose_name='Grupo / Sección')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.studentprofile', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Matrícula Escolar',
                'verbose_name_plural': 'Matrículas Escolares',
                'ordering': ['course_section__grade_level__order', 'student__user__last_name'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
