# Generated by Django 5.1.15 on 2026-09-17 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_institutionsetting'),
        ('periods', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACADEMIC', '📚 Seguimiento Académico'), ('DISCIPLINARY', '⚠️ Convivencial / Disciplinario'), ('ATTENDANCE', '⏰ Asistencia / Puntualidad'), ('CITATION', '📢 Citación a Acudiente'), ('RECOGNITION', '⭐ Felicitación / Mérito')], default='ACADEMIC', max_length=25, verbose_name='Categoría')),
                ('severity', models.CharField(choices=[('INFO', 'Informativa / Positiva'), ('WARNING', 'Llamado de Atención'), ('CRITICAL', 'Falta Grave / Citación Urgente')], default='INFO', max_length=15, verbose_name='Nivel / Severidad')),
                ('title', models.CharField(max_length=150, verbose_name='Título de la Observación')),
                ('description', models.TextField(verbose_name='Descripción de los Hechos')),
                ('commitments', models.TextField(blank=True, null=True, verbose_name='Compromisos del Estudiante / Acuerdos')),
                ('parent_notified', models.BooleanField(default=False, verbose_name='¿Acudiente Notificado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_observations', to='periods.academicperiod', verbose_name='Periodo Lectivo')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_observations', to='courses.academicyear', verbose_name='Año Lectivo')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_observations', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='students.studentprofile', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Observación de Estudiante',
                'verbose_name_plural': 'Observador de Estudiantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
