# Generated by Django 5.1.15 on 2026-09-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentobservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', '🟡 Pendiente de Aprobación'), ('ACTIVE', '🟢 Matriculado / Activo'), ('TRANSFERRED', '🔵 Trasladado de Grupo'), ('WITHDRAWN', '🔴 Retirado / Desertor'), ('PROMOTED', '🎓 Promovido de Grado'), ('FAILED', '❌ No Promovido')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Estado de Matrícula'),
        ),
    ]
