# Generated by Django 5.1.15 on 2026-09-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='admission_requirement_info',
            field=models.CharField(blank=True, default='Requisitos de Admisión al día', max_length=150, verbose_name='Requisito de Admisión (Saber 11 / Prueba Aptitud / Paz y Salvo)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='financial_status',
            field=models.CharField(choices=[('PAZ_Y_SALVO', '🟢 Paz y Salvo'), ('PENDIENTE', '🟡 Pendiente de Pago'), ('MORA', '🔴 En Mora')], default='PAZ_Y_SALVO', max_length=20, verbose_name='Estado Financiero / Tesorería'),
        ),
    ]
