# Generated by Django 5.1.15 on 2026-09-15 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Año Calendario')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre Descriptivo')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Finalización')),
                ('status', models.CharField(choices=[('PLANNING', 'En Planificación'), ('ACTIVE', 'En Curso (Activo)'), ('CLOSED', 'Cerrado / Concluido')], db_index=True, default='PLANNING', max_length=15, verbose_name='Estado')),
                ('is_current', models.BooleanField(db_index=True, default=False, verbose_name='¿Es el Año Vigente Actual?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Año Lectivo',
                'verbose_name_plural': 'Años Lectivos',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Grado')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código de Grado')),
                ('level_stage', models.CharField(choices=[('PRIMARIA', 'Básica Primaria'), ('SECUNDARIA', 'Básica Secundaria'), ('MEDIA', 'Educación Media')], default='SECUNDARIA', max_length=20, verbose_name='Nivel Académico')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Orden Numérico')),
            ],
            options={
                'verbose_name': 'Grado Escolar',
                'verbose_name_plural': 'Grados Escolares',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Identificador del Grupo (ej. 6-A)')),
                ('classroom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aula Asignada')),
                ('capacity', models.PositiveSmallIntegerField(default=35, verbose_name='Cupo Máximo')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Grupo Activo?')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='courses.academicyear', verbose_name='Año Lectivo')),
                ('homeroom_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_sections', to=settings.AUTH_USER_MODEL, verbose_name='Director de Grupo')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='courses.gradelevel', verbose_name='Grado Escolar')),
            ],
            options={
                'verbose_name': 'Curso / Grupo',
                'verbose_name_plural': 'Cursos / Grupos',
                'ordering': ['academic_year', 'grade_level__order', 'name'],
                'unique_together': {('academic_year', 'grade_level', 'name')},
            },
        ),
    ]
