# Generated by Django 5.1.15 on 2026-09-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('COLEGIO', 'Colegio / Escuela (Básica y Media)'), ('UNIVERSIDAD', 'Universidad / Educación Superior'), ('SENA_TECNICO', 'Instituto Técnico / Tecnológico / SENA'), ('ACADEMIA', 'Academia / Educación Continua'), ('OTRO', 'Institución Personalizada')], default='COLEGIO', max_length=20, verbose_name='Tipo de Institución')),
                ('institution_name', models.CharField(default='ACADEMIX', max_length=150, verbose_name='Nombre de la Institución')),
                ('slogan', models.CharField(blank=True, default='Sistema Integral de Gestión Académica y Control Escolar', max_length=255, verbose_name='Lema o Subtítulo')),
                ('term_student', models.CharField(default='Estudiante', max_length=30, verbose_name='Término Alumno (Singular)')),
                ('term_students', models.CharField(default='Estudiantes', max_length=30, verbose_name='Término Alumnos (Plural)')),
                ('term_teacher', models.CharField(default='Docente', max_length=30, verbose_name='Término Profesor (Singular)')),
                ('term_teachers', models.CharField(default='Docentes', max_length=30, verbose_name='Término Profesores (Plural)')),
                ('term_grade', models.CharField(default='Grado', max_length=30, verbose_name='Término Nivel/Grado (ej. Semestre/Grado/Ciclo)')),
                ('term_section', models.CharField(default='Curso', max_length=30, verbose_name='Término Grupo/Curso (ej. Ficha/Curso/Grupo)')),
                ('term_sections', models.CharField(default='Cursos', max_length=30, verbose_name='Término Grupos/Cursos (Plural)')),
                ('term_subject', models.CharField(default='Asignatura', max_length=30, verbose_name='Término Materia (ej. Módulo/Competencia)')),
                ('term_subjects', models.CharField(default='Asignaturas', max_length=30, verbose_name='Término Materias (Plural)')),
                ('term_director', models.CharField(default='Rector(a)', max_length=30, verbose_name='Término Director(a)/Decano(a)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Institucional',
                'verbose_name_plural': 'Configuración Institucional',
            },
        ),
    ]
