# Generated by Django 5.1.15 on 2026-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_institutionsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradelevel',
            options={'ordering': ['institution_type', 'order'], 'verbose_name': 'Grado / Nivel', 'verbose_name_plural': 'Grados / Niveles'},
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='institution_type',
            field=models.CharField(db_index=True, default='COLEGIO', max_length=20, verbose_name='Tipo de Institución'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='code',
            field=models.CharField(max_length=25, verbose_name='Código de Grado'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='level_stage',
            field=models.CharField(choices=[('PRIMARIA', 'Básica Primaria'), ('SECUNDARIA', 'Básica Secundaria'), ('MEDIA', 'Educación Media'), ('SUPERIOR', 'Educación Superior'), ('TECNICO', 'Formación Técnica / Tecnológica'), ('CONTINUA', 'Educación Continua / Cursos')], default='SECUNDARIA', max_length=20, verbose_name='Nivel Académico'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nombre del Grado / Nivel'),
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together={('institution_type', 'code')},
        ),
    ]
