# Generated by Django 5.1.15 on 2026-09-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_gradelevel_options_gradelevel_institution_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='level_stage',
            field=models.CharField(choices=[('PREESCOLAR', 'Educación Preescolar'), ('PRIMARIA', 'Básica Primaria'), ('SECUNDARIA', 'Básica Secundaria'), ('MEDIA', 'Educación Media'), ('SUPERIOR', 'Educación Superior'), ('TECNICO', 'Formación Técnica / Tecnológica'), ('CONTINUA', 'Educación Continua / Cursos')], default='SECUNDARIA', max_length=20, verbose_name='Nivel Académico'),
        ),
    ]
