# Generated by Django 5.1.15 on 2026-09-15 02:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Área')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Orden en Boletines')),
            ],
            options={
                'verbose_name': 'Área de Conocimiento',
                'verbose_name_plural': 'Áreas de Conocimiento',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Asignatura')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código Abreviado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción Curricular')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='subjects.knowledgearea', verbose_name='Área Fundamental')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Horas Semanales (Intensidad)')),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Peso en el Área (%)')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='courses.gradelevel', verbose_name='Grado Escolar')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_grades', to='subjects.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Asignatura en Malla Curricular',
                'verbose_name_plural': 'Malla Curricular por Grado',
                'ordering': ['grade_level__order', 'subject__area__order', 'subject__name'],
                'unique_together': {('grade_level', 'subject')},
            },
        ),
    ]
