# Generated by Django 5.1.15 on 2026-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgearea',
            options={'ordering': ['institution_type', 'order', 'name'], 'verbose_name': 'Área de Conocimiento', 'verbose_name_plural': 'Áreas de Conocimiento'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['institution_type', 'area', 'name'], 'verbose_name': 'Asignatura / Módulo', 'verbose_name_plural': 'Asignaturas / Módulos'},
        ),
        migrations.AddField(
            model_name='knowledgearea',
            name='institution_type',
            field=models.CharField(db_index=True, default='COLEGIO', max_length=20, verbose_name='Tipo de Institución'),
        ),
        migrations.AddField(
            model_name='subject',
            name='institution_type',
            field=models.CharField(db_index=True, default='COLEGIO', max_length=20, verbose_name='Tipo de Institución'),
        ),
        migrations.AlterField(
            model_name='knowledgearea',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Área'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Código Abreviado'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre de la Asignatura / Módulo'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgearea',
            unique_together={('institution_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('institution_type', 'code')},
        ),
    ]
