# Generated by Django 5.1.15 on 2026-09-21 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_knowledgearea_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['institution_type', 'category', 'area', 'name'], 'verbose_name': 'Asignatura / Módulo', 'verbose_name_plural': 'Asignaturas / Módulos'},
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('PRINCIPAL', 'Materia Principal'), ('HUMANISTICA', 'Materia Humanística'), ('ARTE_DEPORTE', 'Arte y Deporte')], default='PRINCIPAL', max_length=20, verbose_name='Agrupación / Categoría'),
        ),
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Créditos Académicos (Superior)'),
        ),
        migrations.CreateModel(
            name='SubjectNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código de Norma / Estándar')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Norma')),
                ('description', models.TextField(verbose_name='Descripción de la Competencia / Estándar')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='subjects.subject', verbose_name='Asignatura / Módulo')),
            ],
            options={
                'verbose_name': 'Norma / Competencia',
                'verbose_name_plural': 'Normas y Competencias',
                'ordering': ['subject', 'order', 'code'],
            },
        ),
    ]
