# Generated by Django 5.1.15 on 2026-09-15 02:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('periods', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Criterio')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Ponderación Porcentual (%)')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Orden en Planilla')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='periods.academicperiod', verbose_name='Periodo Lectivo')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='courses.coursesection', verbose_name='Curso / Sección')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='subjects.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Criterio de Evaluación',
                'verbose_name_plural': 'Criterios de Evaluación',
                'ordering': ['order', 'id'],
                'unique_together': {('course_section', 'subject', 'academic_period', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Calificación (1.00 - 5.00)')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Retroalimentación Docente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='periods.academicperiod', verbose_name='Periodo')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='courses.coursesection', verbose_name='Curso')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='grades.evaluationcriterion', verbose_name='Criterio de Evaluación')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grades', to=settings.AUTH_USER_MODEL, verbose_name='Calificado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='students.studentprofile', verbose_name='Estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='subjects.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['student__user__last_name', 'criterion__order'],
                'unique_together': {('student', 'course_section', 'subject', 'academic_period', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='PeriodFinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota Definitiva Ponderada')),
                ('performance_level', models.CharField(choices=[('BAJO', 'Bajo (1.00 - 2.99)'), ('BASICO', 'Básico (3.00 - 3.99)'), ('ALTO', 'Alto (4.00 - 4.59)'), ('SUPERIOR', 'Superior (4.60 - 5.00)')], default='BASICO', max_length=15, verbose_name='Nivel de Desempeño')),
                ('is_approved', models.BooleanField(default=True, verbose_name='¿Aprobado?')),
                ('recalculated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_final_grades', to='periods.academicperiod', verbose_name='Periodo')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_final_grades', to='courses.coursesection', verbose_name='Curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_final_grades', to='students.studentprofile', verbose_name='Estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_final_grades', to='subjects.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Nota Definitiva de Periodo',
                'verbose_name_plural': 'Notas Definitivas de Periodo',
                'ordering': ['student__user__last_name'],
                'unique_together': {('student', 'course_section', 'subject', 'academic_period')},
            },
        ),
    ]
