# Generated by Django 5.1.15 on 2026-09-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_graderecord_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodfinalgrade',
            name='performance_level',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('BASICO', 'Básico'), ('ALTO', 'Alto'), ('SUPERIOR', 'Superior')], default='BASICO', max_length=15, verbose_name='Nivel de Desempeño'),
        ),
    ]
