# Generated by Django 5.1.15 on 2026-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_periodfinalgrade_performance_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='¿Nota Bloqueada / Inmutable?'),
        ),
    ]
