# Generated by Django 5.1.15 on 2026-09-15 02:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('periods', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título de la Actividad')),
                ('description', models.TextField(verbose_name='Instrucciones y Requisitos')),
                ('due_date', models.DateTimeField(verbose_name='Fecha y Hora Límite de Entrega')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework_attachments/', verbose_name='Guía o Material Adjunto (PDF/Doc)')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Habilitada?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='periods.academicperiod', verbose_name='Periodo Lectivo')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='courses.coursesection', verbose_name='Curso / Sección')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='subjects.subject', verbose_name='Asignatura')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homeworks', to='teachers.teacherprofile', verbose_name='Docente Asignador')),
            ],
            options={
                'verbose_name': 'Tarea Escolar',
                'verbose_name_plural': 'Tareas Escolares',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True, null=True, verbose_name='Comentario de Entrega')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework_submissions/', verbose_name='Archivo de Entrega (Trabajo del Estudiante)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Nota Obtenida (1.00 - 5.00)')),
                ('teacher_feedback', models.TextField(blank=True, null=True, verbose_name='Retroalimentación Docente')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Entregado a Tiempo'), ('LATE', 'Entregado con Retardo'), ('GRADED', 'Calificado y Retroalimentado')], default='SUBMITTED', max_length=20, verbose_name='Estado')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homework', verbose_name='Tarea Asignada')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='students.studentprofile', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Entrega de Tarea',
                'verbose_name_plural': 'Entregas de Tareas',
                'ordering': ['-submitted_at'],
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
