# Generated by Django 5.1.15 on 2026-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_homeworksubmission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='¿Calificación Bloqueada / Inmutable?'),
        ),
    ]
