# Generated by Django 5.1.15 on 2026-09-15 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('periods', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha de la Clase')),
                ('hours_count', models.PositiveSmallIntegerField(default=1, verbose_name='Horas Pedagógicas Impartidas')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones de la Jornada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='periods.academicperiod', verbose_name='Periodo Lectivo')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='courses.coursesection', verbose_name='Curso / Grupo')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='subjects.subject', verbose_name='Asignatura')),
                ('teaching_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='teachers.teachingassignment', verbose_name='Asignación Docente')),
            ],
            options={
                'verbose_name': 'Sesión de Asistencia',
                'verbose_name_plural': 'Sesiones de Asistencia',
                'ordering': ['-date', 'course_section', 'subject'],
                'unique_together': {('course_section', 'subject', 'date', 'academic_period')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', '🟢 Presente'), ('LATE', '⏱️ Tardanza'), ('JUSTIFIED', '📝 Falta Justificada'), ('UNJUSTIFIED', '❌ Falta Injustificada')], db_index=True, default='PRESENT', max_length=20, verbose_name='Estado de Asistencia')),
                ('justification', models.TextField(blank=True, null=True, verbose_name='Motivo de Justificación / Soporte')),
                ('justification_file', models.FileField(blank=True, null=True, upload_to='attendance_justifications/', verbose_name='Comprobante Adjunto (Excusa Médica)')),
                ('is_justified', models.BooleanField(default=False, verbose_name='¿Inasistencia Justificada?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.studentprofile', verbose_name='Estudiante')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession', verbose_name='Sesión de Asistencia')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['student__user__last_name', 'student__user__first_name'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
