# Generated by Django 5.1.15 on 2026-09-15 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=120, verbose_name='Especialidad o Titulación Principal')),
                ('escalafon_grade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Categoría / Escalafón')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Institucional')),
            ],
            options={
                'verbose_name': 'Perfil Docente',
                'verbose_name_plural': 'Perfiles Docentes',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Asignación Activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='courses.academicyear', verbose_name='Año Lectivo')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='courses.coursesection', verbose_name='Curso / Sección')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='subjects.subject', verbose_name='Asignatura')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacherprofile', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Asignación Académica',
                'verbose_name_plural': 'Asignaciones Académicas',
                'ordering': ['course_section__grade_level__order', 'course_section__name', 'subject__name'],
                'unique_together': {('course_section', 'subject', 'academic_year')},
            },
        ),
    ]
