# Generated by Django 5.1.15 on 2026-09-15 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('action', models.CharField(choices=[('INSERT', 'Creación (INSERT)'), ('UPDATE', 'Modificación (UPDATE)'), ('DELETE', 'Eliminación (DELETE)'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('FAILED_LOGIN', 'Intento Fallido de Inicio de Sesión'), ('PERIOD_CLOSE', 'Cierre de Periodo Académico'), ('GRADE_OVERRIDE', 'Modificación Extraordinaria de Nota')], db_index=True, max_length=25, verbose_name='Acción Realizada')),
                ('table_name', models.CharField(db_index=True, max_length=100, verbose_name='Tabla / Entidad Afectada')),
                ('record_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID de Registro Afectado')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Valores Anteriores')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Valores Nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo / Justificación')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['table_name', 'record_id'], name='audit_audit_table_n_dc0494_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx')],
            },
        ),
    ]
