# Generated by Django 5.1.15 on 2026-09-15 02:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('periods', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClosingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_type', models.CharField(choices=[('PERIOD', 'Cierre de Periodo Lectivo'), ('YEAR', 'Cierre Definitivo de Año Escolar')], default='PERIOD', max_length=10, verbose_name='Tipo de Cierre')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Cierre')),
                ('total_students_evaluated', models.PositiveIntegerField(default=0, verbose_name='Total Estudiantes Evaluados')),
                ('total_promoted', models.PositiveIntegerField(default=0, verbose_name='Total Promovidos')),
                ('total_failed', models.PositiveIntegerField(default=0, verbose_name='Total No Promovidos')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones / Justificación')),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_logs', to='periods.academicperiod', verbose_name='Periodo Lectivo')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_logs', to='courses.academicyear', verbose_name='Año Lectivo')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
            ],
            options={
                'verbose_name': 'Bitácora de Cierre Académico',
                'verbose_name_plural': 'Bitácoras de Cierre Académico',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_passing_grade', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Calificación Mínima Aprobatoria')),
                ('max_failed_subjects', models.PositiveSmallIntegerField(default=2, verbose_name='Máximo de Asignaturas Reprobadas Permitidas')),
                ('max_absence_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje Máximo de Inasistencias (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Regla Activa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rule', to='courses.academicyear', verbose_name='Año Lectivo')),
            ],
            options={
                'verbose_name': 'Regla de Promoción',
                'verbose_name_plural': 'Reglas de Promoción',
            },
        ),
        migrations.CreateModel(
            name='AnnualFinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Calificación Definitiva Anual')),
                ('performance_level', models.CharField(choices=[('BAJO', 'Bajo (1.00 - 2.99)'), ('BASICO', 'Básico (3.00 - 3.99)'), ('ALTO', 'Alto (4.00 - 4.59)'), ('SUPERIOR', 'Superior (4.60 - 5.00)')], default='BAJO', max_length=15, verbose_name='Nivel de Desempeño')),
                ('is_approved', models.BooleanField(default=True, verbose_name='¿Asignatura Aprobada?')),
                ('recalculated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_grades', to='courses.academicyear', verbose_name='Año Lectivo')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_grades', to='courses.coursesection', verbose_name='Grupo / Sección')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_grades', to='students.studentprofile', verbose_name='Estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_grades', to='subjects.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Definitiva Anual',
                'verbose_name_plural': 'Definitivas Anuales',
                'ordering': ['student', 'subject'],
                'unique_together': {('student', 'course_section', 'subject', 'academic_year')},
            },
        ),
    ]
