# Generated by Django 5.1.15 on 2026-09-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclosinglog',
            name='rector_signature_authorized',
            field=models.BooleanField(default=True, verbose_name='¿Firma Digital de la Rectora Autorizada en Boletines?'),
        ),
    ]
